# Celox Kamal deployment configuration
# Generated on 2025-07-10 22:57:34
#
# Deploy with: kamal deploy
# Monitor with: kamal logs -f

service: celox
image: johannsg/celox
servers:
  web:
  - 192.168.130.21
proxy:
  ssl: true
  host: celox.me
registry:
  username: johannsg
  password:
  - KAMAL_REGISTRY_PASSWORD
env:
  secret:
  - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
    WEB_CONCURRENCY: 2
    JOB_CONCURRENCY: 3
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
volumes:
- celox_storage:/rails/storage
- celox_db:/rails/db
asset_path: "/rails/public/assets"
builder:
  arch: amd64
