development:
  cleanup_expired_messages:
    class: CleanupExpiredMessagesJob
    queue: default
    schedule: every 2 minutes

production:
  cleanup_expired_messages:
    class: CleanupExpiredMessagesJob
    queue: default
    schedule: every 5 minutes
