# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5227467842fe230d280ed9857af36c37403e4f1af83fbe76e53be6d1369038e70332421b65019673dd5223cf59622a29ba72357b045612e11207d3e6ff4c4a8a

test:
  secret_key_base: efc17f9f1e112a842eaaf0f34cd8c1148e585630296aa751cc6947e5612a66ae398bea61e60bf4961529c768df60a318d886843cc3edfaf403d046a36df9cfe0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
